### ISSUE TITLE
annotation

### ISSUE THREAD

**Issue by Huangqqqhhh** [alloydas/DA-TextSpotter#1]
Thank you very much for your excellent work, I would like to ask if you can send me a copy of the annotation file for the dataset UWT in the model SwinTextSpotter is used for training and testing

**Comment by alloydas** [comment]
Please send an email with your affiliation details to alloyuit@gmail.com to request the dataset. Since it is intended for academic purposes, he will definitely share it with you upon receiving your affiliation information.

**Comment by Huangqqqhhh** [comment]
Thank you！
